### ISSUE TITLE
'SystemInfoKit/SystemInfoKit.h' file not found

### ISSUE THREAD

**Issue by naapki** [jackw01/MicroMonitor#2]
'SystemInfoKit/SystemInfoKit.h' file not found

<img width="657" alt="bez nazwy" src="https://user-images.githubusercontent.com/36900192/41467158-a7ba1f9c-70a5-11e8-9d81-351373855c11.png">
<img width="240" alt="bez nazwy1" src="https://user-images.githubusercontent.com/36900192/41467159-a8010c72-70a5-11e8-9df9-9a67467f7be9.png">

**Comment by naapki** [comment]
Are you?

**Comment by jackw01** [comment]
Not sure what the issue is. Tested on a clean install of MacOS 10.14 Beta 2, Xcode 10 Beta 2 and it builds and runs without any errors.

**Comment by naapki** [comment]
SystemInfoKit.framework it's empty, there are no files in it

**Comment by jackw01** [comment]
https://github.com/jackw01/MicroMonitor/tree/master/SystemInfoKit.framework/Versions/A/Headers

Try cloning the repository again from the latest commit and building.

**Comment by sunmouse** [comment]
Maybe is the link disabled.

path to SystemInfoKit.framework
`rm Headers Modules Resources SystemInfoKit`
`cd A`
`cd Versions`
`rm Current`
`ln -s A Current`
`ln -s Versions/Current/Headers Headers`
`ln -s Versions/Current/Modules Modules`
`ln -s Versions/Current/Resources Resources`
`ln -s Versions/Current/SystemInfoKit SystemInfoKit`

It should be ok!
